"""FastAPI webhook service exposing EVA tools over HTTP."""

import asyncio
import json
from dataclasses import dataclass, field
from collections.abc import Awaitable, Callable
from typing import Any

import uvicorn
from fastapi import FastAPI, HTTPException, Request, WebSocket, WebSocketDisconnect

from eva.assistant.agentic.audit_log import AuditLog
from eva.assistant.tools.tool_executor import ToolExecutor
from eva.utils.logging import get_logger

logger = get_logger(__name__)


@dataclass(slots=True)
class _ConversationRegistration:
    """Webhook routing state for a single external conversation."""

    executor: ToolExecutor
    audit_log: AuditLog = field(default_factory=AuditLog)
    on_end_call: Callable[[], Awaitable[None]] | None = None


class ToolWebhookService:
    """Expose per-conversation tool executors as HTTP webhook endpoints."""

    def __init__(self, port: int = 8888, host: str = "0.0.0.0"):
        self.port = port
        self.host = host

        self._lock = asyncio.Lock()
        self._conversations: dict[str, _ConversationRegistration] = {}
        self._conversation_map: dict[str, str] = {}  # eva_call_id → telnyx_conversation_id
        self._record_ids: dict[str, str] = {}  # eva_call_id → eva_record_id
        self._model_tag: str | None = None  # LLM model tag for DV metadata

        self._app = FastAPI()
        self._server: uvicorn.Server | None = None
        self._server_task: asyncio.Task[None] | None = None
        self._running = False

        self._register_routes()

    @property
    def app(self) -> FastAPI:
        """Return the FastAPI app for in-process tests."""
        return self._app

    async def start(self) -> None:
        """Start the webhook server."""
        if self._running:
            logger.warning("Tool webhook service already running")
            return

        config = uvicorn.Config(
            self._app,
            host=self.host,
            port=self.port,
            log_level="warning",
            lifespan="off",
        )
        self._server = uvicorn.Server(config)
        self._server_task = asyncio.create_task(self._server.serve())
        self._running = True

        while not self._server.started:
            await asyncio.sleep(0.01)

        logger.info(f"Tool webhook service started on http://{self.host}:{self.port}")

    async def stop(self) -> None:
        """Stop the webhook server."""
        if not self._running:
            return

        self._running = False

        if self._server:
            self._server.should_exit = True

        if self._server_task:
            try:
                await asyncio.wait_for(self._server_task, timeout=5.0)
            except asyncio.TimeoutError:
                self._server_task.cancel()
                try:
                    await self._server_task
                except asyncio.CancelledError:
                    pass

        self._server = None
        self._server_task = None
        logger.info("Tool webhook service stopped")

    async def register_conversation(
        self,
        call_id: str,
        executor: ToolExecutor,
        audit_log: AuditLog | None = None,
    ) -> None:
        """Register a conversation call ID to route future webhook requests."""
        registration = _ConversationRegistration(executor=executor, audit_log=audit_log or AuditLog())
        async with self._lock:
            self._conversations[call_id] = registration
        logger.info(f"Registered tool webhook conversation {call_id}")

    async def set_end_call_handler(self, call_id: str, handler: Callable[[], Awaitable[None]]) -> None:
        """Register a callback invoked when the assistant calls the end_call tool."""
        async with self._lock:
            registration = self._conversations.get(call_id)
            if registration is not None:
                registration.on_end_call = handler

    async def register_route_id(self, route_id: str, registration_key: str) -> None:
        """Register an external routing ID so tool webhook requests can be routed.

        The routing ID appears in the webhook URL path (e.g.
        ``/tools/{route_id}/{tool_name}``). For Telnyx telephony bridge calls
        this is the ``eva_call_id`` — a UUID generated by EVA before dialing
        and passed as a custom SIP header (``X-Eva-Call-Id``). The assistant
        resolves it as ``{{eva_call_id}}`` in webhook URLs.

        ``registration_key`` is the key used in :meth:`register_conversation`
        (typically ``output_id``, e.g. ``"1.1.2/trial_0"``).
        """
        async with self._lock:
            registration = self._conversations.get(registration_key)
            if registration is None:
                logger.warning("Cannot register route_id %s: registration key %s not found", route_id, registration_key)
                return
            self._conversations[route_id] = registration
        logger.info("Registered route_id %s for conversation %s", route_id, registration_key)

    async def unregister_conversation(self, call_id: str) -> None:
        """Remove a conversation (and all its aliases) from the webhook registry."""
        async with self._lock:
            registration = self._conversations.pop(call_id, None)
            if registration is not None:
                reg_id = id(registration)
                # Remove all aliases pointing to the same registration
                aliases = [k for k, v in self._conversations.items() if id(v) == reg_id]
                for alias in aliases:
                    del self._conversations[alias]
        logger.info(f"Unregistered tool webhook conversation {call_id}")

    def get_telnyx_conversation_id(self, eva_call_id: str) -> str | None:
        """Return the Telnyx conversation_id for a given eva_call_id, if known."""
        return self._conversation_map.get(eva_call_id)

    def set_record_id(self, eva_call_id: str, record_id: str) -> None:
        """Associate an EVA record_id with an eva_call_id for conversation tagging."""
        self._record_ids[eva_call_id] = record_id

    def set_model_tag(self, model: str) -> None:
        """Set the LLM model tag to stamp on all conversation metadata."""
        self._model_tag = model

    async def get_audit_log(self, call_id: str) -> AuditLog | None:
        """Return the audit log for a registered conversation."""
        async with self._lock:
            registration = self._conversations.get(call_id)
            return registration.audit_log if registration else None

    async def _get_registration(self, call_id: str) -> _ConversationRegistration | None:
        async with self._lock:
            return self._conversations.get(call_id)

    def _register_routes(self) -> None:
        @self._app.get("/health")
        async def health() -> dict[str, str]:
            return {"status": "ok"}

        @self._app.post("/call-control-events")
        async def call_control_events(request: Request) -> dict[str, str]:
            """Acknowledge Telnyx Call Control webhook events (answer, hangup, etc.)."""
            return {"status": "ok"}

        @self._app.post("/dynamic-variables")
        async def dynamic_variables(request: Request) -> dict:
            """Handle Telnyx AI Assistant dynamic variables webhook.

            Extracts eva_call_id (from SIP header) and telnyx_conversation_id,
            stores the mapping for later enrichment, and stamps eva_call_id
            on the conversation metadata for queryability.
            """
            body = await request.json()
            payload = body.get("data", {}).get("payload", {})

            eva_call_id = payload.get("eva_call_id")
            conversation_id = payload.get("telnyx_conversation_id")
            call_control_id = payload.get("call_control_id")

            logger.info(
                "DV webhook: eva_call_id=%s, conversation_id=%s, cc_id=%s",
                eva_call_id, conversation_id, call_control_id,
            )

            # Store mapping for enrichment
            if eva_call_id and conversation_id:
                self._conversation_map[eva_call_id] = conversation_id
                logger.info(
                    "Stored conversation mapping: %s → %s",
                    eva_call_id, conversation_id,
                )

            response: dict = {"dynamic_variables": {}}
            if eva_call_id:
                response["dynamic_variables"]["eva_call_id"] = eva_call_id
                metadata: dict[str, str] = {"eva_call_id": eva_call_id}
                # Tag with record_id if registered (for filtering conversations by scenario)
                record_id = self._record_ids.get(eva_call_id)
                if record_id:
                    metadata["eva_record_id"] = record_id
                if self._model_tag:
                    metadata["eva_llm_model"] = self._model_tag
                response["conversation"] = {"metadata": metadata}
            return response

        @self._app.post("/tools/{call_id}/{tool_name}")
        async def invoke_tool(call_id: str, tool_name: str, request: Request) -> Any:
            registration = await self._get_registration(call_id)
            if registration is None:
                # Try URL-decoded version (session IDs shouldn't need this,
                # but call_control_ids contained colons — keep as safety net)
                from urllib.parse import unquote
                registration = await self._get_registration(unquote(call_id))
            if registration is None:
                logger.warning(
                    "Tool webhook 404: call_id=%s not found in registered conversations",
                    call_id,
                )
                raise HTTPException(status_code=404, detail=f"Unknown call_id: {call_id}")

            try:
                body = await request.json()
            except Exception as exc:
                raise HTTPException(status_code=400, detail="Invalid JSON request body") from exc

            if body is None:
                params: dict[str, Any] = {}
            elif isinstance(body, dict):
                function_params = body.get("function_params")
                if function_params is None:
                    params = body
                elif isinstance(function_params, dict):
                    params = function_params
                else:
                    raise HTTPException(status_code=400, detail="function_params must be a JSON object")
            else:
                raise HTTPException(status_code=400, detail="Tool webhook body must be a JSON object")

            registration.audit_log.append_tool_call(tool_name, params)

            # Handle end_call: trigger hangup via the registered callback.
            if tool_name == "end_call" and registration.on_end_call is not None:
                registration.audit_log.append_tool_response(tool_name, {"status": "call_ended"})
                logger.info("end_call tool invoked for call %s — triggering hangup", call_id)
                asyncio.create_task(registration.on_end_call())
                return {"status": "call_ended"}

            result = await registration.executor.execute(tool_name, params)
            registration.audit_log.append_tool_response(tool_name, result)

            logger.info(f"Executed webhook tool {tool_name} for call {call_id}")
            return result

        @self._app.websocket("/media-stream/{conversation_id:path}")
        async def media_stream(websocket: WebSocket, conversation_id: str) -> None:
            """Accept Telnyx Call Control media stream connections."""
            from eva.assistant.transports.call_control import get_active_transport

            transport = await get_active_transport(conversation_id)
            if transport is None:
                logger.warning("No active transport for media stream conversation %s", conversation_id)
                await websocket.close(code=1008, reason="No active transport for this conversation")
                return

            await websocket.accept()
            logger.info("Accepted media stream WebSocket for conversation %s", conversation_id)
            try:
                await transport.handle_media_stream(websocket)
            except WebSocketDisconnect:
                logger.info("Media stream WebSocket disconnected for %s", conversation_id)
            except Exception as exc:
                logger.error("Media stream error for %s: %s", conversation_id, exc)
