"""Unit tests for Telnyx assistant setup helpers."""

from typing import Any

import pytest

from eva.assistant.telnyx_setup import TelnyxAssistantManager
from eva.models.agents import AgentConfig


class _FakeResponse:
    def __init__(self, status: int, payload: dict[str, Any]):
        self.status = status
        self._payload = payload

    async def __aenter__(self) -> "_FakeResponse":
        return self

    async def __aexit__(self, exc_type, exc, tb) -> None:
        return None

    async def json(self) -> dict[str, Any]:
        return self._payload

    async def text(self) -> str:
        return str(self._payload)


class _FakeSession:
    def __init__(self) -> None:
        self.requests: list[tuple[str, str, dict[str, Any] | None]] = []
        self.closed = False

    def post(self, url: str, json: dict[str, Any]) -> _FakeResponse:
        self.requests.append(("POST", url, json))
        return _FakeResponse(201, {"id": "assistant-123"})

    def delete(self, url: str) -> _FakeResponse:
        self.requests.append(("DELETE", url, None))
        return _FakeResponse(200, {"id": "assistant-123", "deleted": True})

    async def close(self) -> None:
        self.closed = True


def _make_agent_config() -> AgentConfig:
    return AgentConfig.model_validate(
        {
            "id": "airline-agent",
            "name": "Airline Agent",
            "description": "Assist callers with airline reservations.",
            "role": "Reservation specialist",
            "instructions": "Verify the reservation before making changes.",
            "personality": "Calm and efficient.",
            "tool_module_path": "eva.assistant.tools.airline_tools",
            "tools": [
                {
                    "id": "get_reservation",
                    "name": "Get Reservation",
                    "description": "Look up a reservation by confirmation number",
                    "required_parameters": [
                        {
                            "name": "confirmation_number",
                            "type": "string",
                            "description": "The booking confirmation number",
                        }
                    ],
                }
            ],
        }
    )


class TestTelnyxAssistantManager:
    @pytest.mark.asyncio
    async def test_create_benchmark_assistant_builds_webhook_tool_payload(self) -> None:
        session = _FakeSession()
        manager = TelnyxAssistantManager(api_key="test-key", session=session)  # type: ignore[arg-type]

        assistant_id = await manager.create_benchmark_assistant(
            agent_config=_make_agent_config(),
            agent_config_path="configs/agents/airline_agent.yaml",
            webhook_base_url="https://example.ngrok-free.app/",
            model="telnyx-llm-gpt-4o",
            voice="alloy",
        )

        assert assistant_id == "assistant-123"
        assert len(session.requests) == 1
        method, url, payload = session.requests[0]
        assert method == "POST"
        assert url == "https://api.telnyx.com/v2/ai/assistants"
        assert payload is not None
        assert payload["model"] == "telnyx-llm-gpt-4o"
        assert payload["voice_settings"]["voice"] == "alloy"
        assert payload["telephony_settings"]["supports_unauthenticated_web_calls"] is True
        # Check tool structure (allow extra fields like timeout_ms, path_parameters, etc.)
        assert len(payload["tools"]) >= 1
        webhook_tool = payload["tools"][0]
        assert webhook_tool["type"] == "webhook"
        wh = webhook_tool["webhook"]
        assert wh["name"] == "get_reservation"
        assert wh["url"] == "https://example.ngrok-free.app/tools/{{call_session_id}}/get_reservation"
        assert wh["method"] == "POST"
        assert "confirmation_number" in wh["body_parameters"]["properties"]
        assert "Role: Reservation specialist" in payload["instructions"]
        assert "Calm and efficient." in payload["instructions"]
        assert payload["description"].startswith("Auto-generated by EVA")

    @pytest.mark.asyncio
    async def test_delete_assistant_uses_delete_endpoint(self) -> None:
        session = _FakeSession()
        manager = TelnyxAssistantManager(api_key="test-key", session=session)  # type: ignore[arg-type]

        await manager.delete_assistant("assistant-123")

        assert session.requests == [
            ("DELETE", "https://api.telnyx.com/v2/ai/assistants/assistant-123", None),
        ]

    @pytest.mark.asyncio
    async def test_close_closes_owned_session(self) -> None:
        manager = TelnyxAssistantManager(api_key="test-key")

        await manager.close()

        assert manager.session.closed is True
