"""Unit tests for Telnyx assistant setup helpers."""

import importlib
import inspect
import re
from pathlib import Path
from typing import Any

import pytest
import yaml

from eva.assistant.external.providers.telnyx.setup import TelnyxAssistantManager
from eva.models.agents import AgentConfig, AgentsConfig


class _FakeResponse:
    def __init__(self, status: int, payload: dict[str, Any]):
        self.status = status
        self._payload = payload

    async def __aenter__(self) -> "_FakeResponse":
        return self

    async def __aexit__(self, exc_type, exc, tb) -> None:
        return None

    async def json(self) -> dict[str, Any]:
        return self._payload

    async def text(self) -> str:
        return str(self._payload)


class _FakeSession:
    def __init__(self) -> None:
        self.requests: list[tuple[str, str, dict[str, Any] | None]] = []
        self.closed = False

    def post(self, url: str, json: dict[str, Any]) -> _FakeResponse:
        self.requests.append(("POST", url, json))
        return _FakeResponse(201, {"id": "assistant-123"})

    def delete(self, url: str) -> _FakeResponse:
        self.requests.append(("DELETE", url, None))
        return _FakeResponse(200, {"id": "assistant-123", "deleted": True})

    async def close(self) -> None:
        self.closed = True


def _make_agent_config() -> AgentConfig:
    return AgentConfig.model_validate(
        {
            "id": "airline-agent",
            "name": "Airline Agent",
            "description": "Assist callers with airline reservations.",
            "role": "Reservation specialist",
            "instructions": "Verify the reservation before making changes.",
            "personality": "Calm and efficient.",
            "tool_module_path": "eva.assistant.tools.airline_tools",
            "tools": [
                {
                    "id": "get_reservation",
                    "name": "Get Reservation",
                    "description": "Look up a reservation by confirmation number",
                    "required_parameters": [
                        {
                            "name": "confirmation_number",
                            "type": "string",
                            "description": "The booking confirmation number",
                        }
                    ],
                }
            ],
        }
    )


class TestTelnyxAssistantManager:
    @pytest.mark.asyncio
    async def test_create_benchmark_assistant_builds_webhook_tool_payload(self) -> None:
        session = _FakeSession()
        manager = TelnyxAssistantManager(api_key="test-key", session=session)  # type: ignore[arg-type]

        assistant_id = await manager.create_benchmark_assistant(
            agent_config=_make_agent_config(),
            agent_config_path="configs/agents/airline_agent.yaml",
            webhook_base_url="https://example.ngrok-free.app/",
            model="telnyx-llm-gpt-4o",
            voice="alloy",
        )

        assert assistant_id == "assistant-123"
        assert len(session.requests) == 1
        method, url, payload = session.requests[0]
        assert method == "POST"
        assert url == "https://api.telnyx.com/v2/ai/assistants"
        assert payload is not None
        assert payload["model"] == "telnyx-llm-gpt-4o"
        assert payload["voice_settings"]["voice"] == "alloy"
        assert payload["telephony_settings"]["supports_unauthenticated_web_calls"] is True
        # Check tool structure (allow extra fields like timeout_ms, path_parameters, etc.)
        assert len(payload["tools"]) >= 1
        webhook_tool = payload["tools"][0]
        assert webhook_tool["type"] == "webhook"
        wh = webhook_tool["webhook"]
        assert wh["name"] == "get_reservation"
        assert wh["url"] == "https://example.ngrok-free.app/tools/{{eva_call_id}}/get_reservation"
        assert wh["method"] == "POST"
        assert "confirmation_number" in wh["body_parameters"]["properties"]
        assert "Role: Reservation specialist" in payload["instructions"]
        assert "Calm and efficient." in payload["instructions"]
        assert payload["description"].startswith("Auto-generated by EVA")

    @pytest.mark.asyncio
    async def test_delete_assistant_uses_delete_endpoint(self) -> None:
        session = _FakeSession()
        manager = TelnyxAssistantManager(api_key="test-key", session=session)  # type: ignore[arg-type]

        await manager.delete_assistant("assistant-123")

        assert session.requests == [
            ("DELETE", "https://api.telnyx.com/v2/ai/assistants/assistant-123", None),
        ]

    @pytest.mark.asyncio
    async def test_close_closes_owned_session(self) -> None:
        manager = TelnyxAssistantManager(api_key="test-key")

        await manager.close()

        assert manager.session.closed is True


# ---------------------------------------------------------------------------
# Regression guards — detect upstream changes that break our Telnyx integration
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parents[3]
_AGENT_CONFIG_PATH = _REPO_ROOT / "configs" / "agents" / "airline_agent.yaml"


def _load_real_agent_config() -> AgentConfig:
    """Load the actual airline agent config from the repo."""
    with open(_AGENT_CONFIG_PATH) as f:
        raw = yaml.safe_load(f)
    return AgentConfig.model_validate(raw)


def _build_payload_from_real_config() -> dict[str, Any]:
    """Build the Telnyx assistant payload from the real airline agent config.

    Uses the private static method directly to avoid needing an event loop
    for aiohttp.ClientSession initialization.
    """
    agent_config = _load_real_agent_config()
    # Call the instance method on a throwaway object — but we can't create one
    # without an event loop. Instead, call the static helper directly and
    # build the wrapper ourselves.
    normalized_base = "https://example.ngrok-free.dev"
    tools: list[dict[str, Any]] = [
        TelnyxAssistantManager._build_webhook_tool(tool, normalized_base)
        for tool in agent_config.tools
    ]
    tools.append({
        "type": "hangup",
        "hangup": {"description": "Hang up the call."},
    })
    return {"tools": tools, "agent_config": agent_config}


class TestTelnyxRegressionGuards:
    """Tests that fail when upstream changes aren't reflected in Telnyx setup."""

    def test_every_agent_tool_produces_a_webhook_entry(self) -> None:
        """If a tool is added to airline_agent.yaml, telnyx_setup must translate it."""
        result = _build_payload_from_real_config()
        agent_config = result["agent_config"]
        tools = result["tools"]

        webhook_tools = [t for t in tools if t["type"] == "webhook"]
        config_tool_ids = {t.id for t in agent_config.tools}
        webhook_tool_ids = {t["webhook"]["name"] for t in webhook_tools}

        assert config_tool_ids == webhook_tool_ids, (
            f"Tool mismatch: config has {config_tool_ids - webhook_tool_ids} not in webhooks, "
            f"webhooks have {webhook_tool_ids - config_tool_ids} not in config"
        )

    def test_tool_module_functions_match_agent_config(self) -> None:
        """Every tool in the YAML must have a matching function in the tool module.

        Catches: upstream adds a tool to the config but forgets the implementation,
        or renames a function without updating the config.
        """
        agent_config = _load_real_agent_config()
        module = importlib.import_module(agent_config.tool_module_path)
        module_functions = {
            name
            for name, obj in inspect.getmembers(module, inspect.isfunction)
            if not name.startswith("_") and name != "validation_error_response"
        }
        config_tool_ids = {t.id for t in agent_config.tools}

        missing_impl = config_tool_ids - module_functions
        assert not missing_impl, (
            f"Tools in config but not in {agent_config.tool_module_path}: {missing_impl}"
        )

    def test_all_webhook_urls_use_eva_call_id(self) -> None:
        """Webhook URLs must use {{eva_call_id}} for concurrent call routing."""
        result = _build_payload_from_real_config()

        for tool in result["tools"]:
            if tool["type"] != "webhook":
                continue
            url = tool["webhook"]["url"]
            assert "{{eva_call_id}}" in url, (
                f"Tool {tool['webhook']['name']} uses wrong URL template: {url}"
            )
            assert "{{call_control_id}}" not in url, (
                f"Tool {tool['webhook']['name']} still uses call_control_id: {url}"
            )
            assert "{{call_session_id}}" not in url, (
                f"Tool {tool['webhook']['name']} still uses call_session_id: {url}"
            )

    def test_webhook_tool_payload_has_required_fields(self) -> None:
        """Every webhook tool must have the fields the Telnyx API expects.

        Catches: refactoring _build_webhook_tool and dropping a required field.
        """
        result = _build_payload_from_real_config()

        for tool in result["tools"]:
            if tool["type"] != "webhook":
                continue
            wh = tool["webhook"]
            assert "name" in wh, f"Missing 'name' in webhook tool"
            assert "url" in wh, f"Missing 'url' in webhook tool {wh.get('name')}"
            assert "method" in wh, f"Missing 'method' in webhook tool {wh.get('name')}"
            assert "body_parameters" in wh, f"Missing 'body_parameters' in webhook tool {wh.get('name')}"
            assert wh["body_parameters"].get("type") == "object", (
                f"body_parameters.type should be 'object' for {wh['name']}"
            )

    def test_hangup_tool_always_present(self) -> None:
        """Telnyx assistants need a hangup tool — make sure we always include it."""
        result = _build_payload_from_real_config()

        tool_types = [t["type"] for t in result["tools"]]
        assert "hangup" in tool_types, "Hangup tool missing from assistant payload"
